catalog:
  '@cloudflare/containers': ^0.0.22
  dev: ^0.1.3
  hono: ^4.8.5
  wrangler: ^4.24.3

catalogs:
  cli:
    '@antfu/eslint-config': ^4.16.2
    '@antfu/ni': ^24.4.0
    eslint: ^9.31.0
    lint-staged: ^15.5.2
    simple-git-hooks: ^2.13.0
    typescript: ^5.8.3
    vite: ^6.3.5
  dev:
    unbuild: ^3.5.0
  testing:
    '@cloudflare/vitest-pool-workers': ^0.8.53
    vitest: ^3.2.4
  types:
    '@types/node': ^24.0.13
    jiti: ^2.4.2
onlyBuiltDependencies:
  - esbuild
  - simple-git-hooks
