catalog:
  '@cloudflare/containers': ^0.0.0
  dev: ^0.1.3
  hono: ^4.8.4
  wrangler: ^0.0.0

catalogs:
  cli:
    '@antfu/eslint-config': ^4.10.1
    '@antfu/ni': ^24.1.0
    eslint: ^9.22.0
    lint-staged: ^15.5.0
    simple-git-hooks: ^2.11.1
    typescript: ^5.8.2
    vite: ^6.2.1
  dev:
    vitest: ^3.2.4
  types:
    '@types/node': ^24.0.13

onlyBuiltDependencies:
  - esbuild
  - simple-git-hooks
